### ISSUE TITLE
Review: 피드백 요청

### ISSUE THREAD

**Issue by InSeong-So** [subscriptionRescueTeam/save-my-youth#118]
## 개요
잘 읽었습니다! 🙌
관련 피드백 몇개 남깁니다. 다들 고생 많으셨어요~

<br>

## 내용

~~- 저장소 루트 경로에 `package-lock.json`은 없어도 될 것 같네요.~~ (해결)

~~- `save-my-youth/blob/dev/frontend/src/index.d.ts`가 덩그러니 있는 이유는 무엇일까요?~~ (해결)
 ~~- tsconfig의 `typeRoots` 옵션을 활용하면 좋겠습니다!~~

~~- font.css의 역할은 결국 전역적으로 font-face를 선언하는 데 있다고 봅니다. 그러면 Global Style과 같이 묶여 있는 게 자연스러울 것 같아요.~~ (해결)
  ~~- App.tsx에 정의된 GlobalStyle을 분리해서 font.css와 통합하는 건 어떨까요?~~

~~- `save-my-youth/blob/dev/frontend/src/utils/api.tsx`에 axios를 import 한 이유는 무엇일까요?~~(해결)
  ~~- 또한 성질로는 유틸리티적인 요소보다 상수를 정의한 파일 같아 보여요.~~

~~- `save-my-youth/blob/dev/frontend/src/types/index.ts`에 한글로 타입을 선언했는데... 모든 타입을 한글로 선언한 게 아니라 의아하네요.~~ (해결)
~~- 한글 자체가 문제되기보다, 일관성 있게 작성하면 좋겠습니다.~~

~~- 이어서, `Array<청약>`과 `청약[]`의 차이를 알고 있을까요? 일관성 있는 타입 선언을 위해 어떤 걸 선택하면 좋을까요?~~

~~- `save-my-youth/blob/dev/frontend/src/constants/color.ts` 이런 파일은 보통 palette라고 정의하는데, 찾아보시면 좋겠어요.~~ (해결)
  ~~- 객체로 관리되는 상수이므로, 충분히 변경 가능성이 있습니다. 자바스크립트에서는 Object.freeze를 사용해서 객체를 불변하게 만들겠지만...~~
  ~~- 타입스크립트는 어떨까요? 어떤 방법을 쓰면 안전하게 선언할 수 있을까요?~~
  ~~- *힌트는 위에 언급한 배열 타입과 연관이 있습니다.~~

~~- asset은 뭘까요? 무슨 의미를 가진 폴더일까요? 고민해보면 좋겠습니다.~~ (해결)
  ~~- 우선 내부 파일"들"이 존재하므로 복수형이 옳아보여요.~~
  ~~- 내부에 `*.tsx`로 선언된 파일이 많은데, 왜 이렇게 관리했을까요? `*.d.ts`를 알아보면 좋겠습니다.~~
  ~~- 확장자가 다르다면 분명 다른 이유가 있는 이미지 파일이라 생각해요. 폴더를 분리하고 적절한 네이밍을 찾아보세요.~~

~~- `save-my-youth/blob/dev/frontend/src/hooks/useSubscription.tsx`은... 내부에서 외부 변수를 수정하고, 내부 변수에서 다이나믹하게 변경되고, 상수로 관리될 수 있는 문자열이 하드코딩 되어 있네요. 어떻게 정리할 수 있을까요? 안티 패턴이 상당히 많이 보입니다.~~ (해결)

~~- `save-my-youth/blob/dev/frontend/src/components/Card/index.tsx` let으로 `useNavigate()`를 선언한 이유는 무엇일까요?~~
  ~~- components는 동일한 피드백이 가능하겠네요. 스타일링과 로직이 혼재하여 알아보기 힘든 감이 없잖아 있습니다. 또한 폴더 > index.tsx로 지칭할 것이라면, `Card.tsx`로 선언하면 어떨까요?~~
  ~~- `{ children: React.ReactNode; }` 타입이 많이 보입니다. types 하위로 잘 공통화시킬 수 있을 것 같아요.~~

~~- 404 페이지는 없는 걸까요? 실제 서비스 링크에서 임의 url을 이동하면 흰 화면만 출력되네요.~~ (해결)

<br>

**Comment by jwun95** [comment]
피드백 감사드립니다. 일요일 스터디에서 뵙겠습니다 ㅎㅎ

**Comment by tooooo1** [comment]
오~~@@@ 너무너무 대박이에요. 감사합니다 파랑! 찬찬히 잘보겠습니다!

**Comment by hotbreakb** [comment]
읽어봤는데 생각해봐야 할 부분을 많이 집어주셨네요. 정말 감사합니다 🙏

**Comment by Lela12** [comment]
피드백 감사합니다 고민을 해보면서 리팩토링 해보도록 하겠습니다 감사합니다!! 👍 👍

**Comment by kmin-jeong** [comment]
피드백 감사합니다!!! 생각해야 할 부분과 모르는 부분 더 공부하면서 리팩토링 해보도록 하겠습니다!! 정말 감사합니다!!!
