### ISSUE TITLE
Feat: ui보완 => 검색기능 구현(엔터치면 리스트 나오게)

### ISSUE THREAD

**Issue by kmin-jeong** [subscriptionRescueTeam/save-my-youth#21]
### Issue Type (하나 이상의 Issue 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### Description
ui를 보완하고 오픈 api를 추후에 연동

**Comment by hotbreakb** [comment]
타로, 나중에 PR 이름 맞춰서 수정해 주세요☺️
